[workspace]
channels = ["conda-forge"]
name = "badgercompute-binder-example"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
seaborn = ">=0.13.2,<0.14"
